F
======================================================================
FAIL: test_compile (rnvs_tb.common.CompileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rnvs_tb/common.py", line 564, in test_compile
    self.assertIn(result, [MAKEFILE_SUCCESSFUL, CMAKE_SUCCESSFUL], msg='Failed to compile binaries!')
AssertionError: -1 not found in [1, 2] : Failed to compile binaries!

----------------------------------------------------------------------
Ran 1 test in 1.978s

FAILED (failures=1)
